services:
  - type: web
    name: backend
    env: node
    buildCommand: "cd backend && npm install"        # Install dependencies inside the backend folder
    startCommand: "cd backend && node index.js"          # Run the start command inside the backend folder
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://your-backend.onrender.com    # This should work if React frontend uses it
